
#Eurecel 既是注册方，也是申请方
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    reister-with-eureka: false
spring:
  application:
    name: eureka
server:
  port: 8762