eureka:
  client:
    service-url :
      default-Zone : http://localhost:8761/eureka/
  instance:
    hostname : order
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
server:
  port: 8081

