eureka:
  client:
    service-url :
      default-Zone : http://localhost:8761/eureka/
  instance:
    hostname : order
    # 是否显示ip,如果不设置那么就会显示主机名，默认false
    prefer-ip-address: true
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
server:
  port: 8081

#https://www.docs4dev.com/amp/docs/zh/spring-cloud/Edgware.SR5/reference/multi_spring-cloud-ribbon.html#_customizing_default_for_all_ribbon_clients
#文档位置
PRODUCT:
  ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
